### ISSUE TITLE
i need lisp setting

### ISSUE THREAD

**Issue by xendia100** [ArturoDent/custom-comments#1]
![Greenshot 2022-01-29 03 02 56](https://user-images.githubusercontent.com/96650095/151598537-624df809-6168-454c-82b7-dc1dbd1075df.png)
could you add lisp
![Greenshot 2022-01-29 03 05 25](https://user-images.githubusercontent.com/96650095/151598775-c9b868c8-cde9-4045-a160-9dd3bff780c5.png)

**Comment by ArturoDent** [comment]
I have added it to v0.4.0.  So this should work:

```jsonc
"custom-language-properties": {
  "lisp.comments.lineComment": "; "
}
```

You should get intellisense for `lisp` and then after `lisp.` for `comments.lineComment`, etc.

Let me know if this works for you.  Thanks.

**Comment by gintering1000** [comment]
![Screen Capture 2022-02-06 at 17 04 47](https://user-images.githubusercontent.com/77244047/152672490-1cd73e21-ce12-40b6-9069-48ee7f382f05.gif)
![image](https://user-images.githubusercontent.com/77244047/152672511-37a06a42-4d1d-4f55-8f0b-5bae51702d13.png)

yes it works. but my setting is ";". but basically one space is more added like image.

**Comment by ArturoDent** [comment]
Do you have this setting enabled:

`Editor > Comments: Insert Space`
