### ISSUE TITLE
Does this plugin work in remote development situation?

### ISSUE THREAD

**Issue by LockeCipher** [ArturoDent/custom-comments#3]
In this situation:

Home PC connected company VPN, and have installed a plugin named Remote Development , version 0.21.0, 

So that I can connect my company PC and coding which I need not save any code in my home PC. 

I found the plugin "Custom Language Properties" does not work. 

<img width="408" alt="image" src="https://user-images.githubusercontent.com/19609874/160739372-ff50179f-3702-4627-a6ba-65c282ed1988.png">

I have checked, home PC and remote PC already install this plugin, and I set all the settings.json I could find, like below

<img width="846" alt="image" src="https://user-images.githubusercontent.com/19609874/160739571-681d5aa5-219f-46b6-b2b6-4a3d64eefc17.png">

So I want to know, does this plugin work in this situation? Or did I do something wrong.

**Comment by LockeCipher** [comment]
I update home system and remote system plugin to version 0.5.3
I tested on home pc and compant pc respectively and it all worked
But if I use home pc connect to company pc, this plugin will failed, like below

<img width="2501" alt="image" src="https://user-images.githubusercontent.com/19609874/160742240-0baee07d-5354-446e-81da-613b5003fd05.png">

**Comment by ArturoDent** [comment]
I tried another thing, so wait for v0.5.4 to land (it takes a few minutes to be published).

Did you try to run the step 2 command from the SO question both locally and on the remote machine?

**Comment by zilianghu** [comment]
> I tried another thing, so wait for v0.5.4 to land (it takes a few minutes to be published).
> 
> Did you try to run the step 2 command from the SO question both locally and on the remote machine?

**Comment by LockeCipher** [comment]
yes, i have tried to run "ustom Language Properties: Check for new language extensions" both locally and remote

**Comment by ArturoDent** [comment]
Did you mean to close this issue?

**Comment by LockeCipher** [comment]
Sorry, I click the wrong button. Please ignore. I'm checking my local and remote machine, whether threre are some configuration files are incorrect.

**Comment by LockeCipher** [comment]
I found plugin update to version 0.5.4, It still not worked in remote development situation.

**Comment by ArturoDent** [comment]
Have you reviewed https://code.visualstudio.com/docs/remote/remote-overview and installed that `Remote Development Extension`?

See this tutorial: https://www.askmecode.com/blog/how-to-set-up-the-remote-development-environment-for-the-vscode/

I have enabled this extension to work on remote or local machines - and you say that it does work on both separately.  So it would appear to be some factor out of the extension's control.  The above links might help, particularly the `Remote Development Extension`.

**Comment by ArturoDent** [comment]
Closing as it is not clear issue isn't related to remote setup and follow-up needed.

**Comment by vanbang9710** [comment]
I also have this problem. 
Whenever I connect to wsl, this error occurs 
```
Cannot activate the 'Custom Language Properties' extension
because it depends on the 'Git' extension, which is not loaded.
Would you like to reload the window to load the extension?
```
Maybe the Git extension is loaded after this extension?
![|50pct](https://i.imgur.com/M9Foc27.png) ![|50pct](https://i.imgur.com/lVzpqQA.png)
After that, the extension doesn't work. Running any command produces error Command not found ![|50pct](https://i.imgur.com/03FTWMM.png)

**Comment by Cryxto** [comment]
yep WSL issue still hapenned in 0.63

> I also have this problem. Whenever I connect to wsl, this error occurs
> 
> ```
> Cannot activate the 'Custom Language Properties' extension
> because it depends on the 'Git' extension, which is not loaded.
> Would you like to reload the window to load the extension?
> ```
> 
> Maybe the Git extension is loaded after this extension? ![|50pct](https://camo.githubusercontent.com/1452954c017e5ad7ad2440735462af806d4d759609f54236257d834f0db68336/68747470733a2f2f692e696d6775722e636f6d2f4d39466f6332372e706e67) ![|50pct](https://camo.githubusercontent.com/c8544bc0dfa7bb910b8d3269735a9bec57a17240df5ca166a777b5ef754aa530/68747470733a2f2f692e696d6775722e636f6d2f6c567a707151412e706e67) After that, the extension doesn't work. Running any command produces error Command not found ![|50pct](https://camo.githubusercontent.com/1ed40869b4b1753fa5872891fa7c829b61da5bfe9f47278a16b0902e6e9b47cd/68747470733a2f2f692e696d6775722e636f6d2f30334654574d4d2e706e67)
