### ISSUE TITLE
Feature request: do not add " " unless it is part of the string

### ISSUE THREAD

**Issue by dimateos** [ArturoDent/custom-comments#4]
Hello! Thanks for the extension, it is very interesting indeed!

I was trying to get the default `"// "` to be `"//"` _without spaces_. Is there a reason why the extension adds it too?

Could it be skipped and just use the string specified in the settings? The user could just add the space there. There could also be a global setting to enable the addition of the space to preserve the current behavior.

Going further, for me it would be nice if that setting would be able to disable the space added in vscode by default to comments too. This way I would not have to write configs for all languages removing it, etc.

Cheers

**Comment by ArturoDent** [comment]
Hi, the extension checks and respects this general setting:

```jsonc
Editor > Comments: Insert Space
```

You can disable that setting and this extension will not add the space after `//`, or you could disable that setting for specific languages.

**Comment by dimateos** [comment]
Thanks so much for the tip!

I guess it was a long time ago when I tried to look for that setting :)

Then the extension works as expected, feel free to close the issue whenever you want.
Thanks.
