### ISSUE TITLE
Cannot read properties of undefined (reading 'charAt')

### ISSUE THREAD

**Issue by mofazhe** [ArturoDent/custom-comments#5]
add setting: 
"custom-language-properties": {
        "ini.comments.lineComment": "#"
}
than open ini file
![image](https://github.com/ArturoDent/custom-language-properties/assets/41715438/fcf9277a-63e5-4a42-be75-3c3a58fad0a7)

ext version v0.6.0
vscode version: 1.83.0

**Comment by dimateos** [comment]
Same issue here with the last version `v0.6.0` and the following vscode:

    Version: 1.83.1 (system setup)
    Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
    Date: 2023-10-10T23:48:05.904Z
    Electron: 25.8.4
    ElectronBuildId: 24154031
    Chromium: 114.0.5735.289
    Node.js: 18.15.0
    V8: 11.4.183.29-electron.0
    OS: Windows_NT x64 10.0.19044

My config that still works with `v0.5.4`:

    "custom-language-properties": {
        "bat.comments.lineComment": "::",
    },

So a temporal solution is to manually change the extension version in vscode.

> Will test other configs to see if this is an issue with the last version requiring other fields in the json and so breaks with older configs.

**Comment by arathburgos05** [comment]
@dimateos

How did you change the version? I didn't see the option to downgrade it in VSCode Marketplace or tags/releases in this repo.

Regards.

**Comment by dimateos** [comment]
Is a bit hidden I guess. You have to click on the little down-arrow right to the Unistall button:

![2023-11-06_(083110)_Code](https://github.com/ArturoDent/custom-language-properties/assets/26868611/cda3684e-354b-40e9-8aaf-ca0be356b735)

**Comment by ArturoDent** [comment]
Apparently it is related to the support I added for `AutoClosingPairs` which was recently added  to the extension api.  But that support is buggy.

I removed support for `AutoClosingPairs` in v0.6.1.

Please test that version and let me know if it back working for you.

Thank you for filing this issue.

**Comment by dimateos** [comment]
Yep no longer happening in `v0.6.1`.

Thanks for your extensions Arturo!

**Comment by mofazhe** [comment]
Yes, it works fine on v0.6.1. Thanks.
