### ISSUE TITLE
Can't utilize the opening & closing functionality of comments 

### ISSUE THREAD

**Issue by ianwieds** [ArturoDent/custom-comments#6]
I want to change liquids comment so instead of `{% comment %}` and  `{% endcomment %}` it does `<!--` and `-->`. However, I can not get the extension to do it and I believe it is a bug.

I have tried this but it has no effect (when I try to comment, nothing happens in the editor)
```
  "custom-language-properties": {
    "liquid.comments.lineComment": ["<!--", "-->"],
  },
```

I have confirmed that this (for example) does actually insert the `<!--` but that is obviously only half of what we need 😂
```
  "custom-language-properties": {
    "liquid.comments.lineComment": "<!--",
  },
```

Otherwise, this looks like it will be a great extension thank you so much for putting this out there!

**Comment by ArturoDent** [comment]
It looks like you should be using:

```
    "liquid.comments.blockComment": ["<!--", "-->"],
```

That works for me.  Using the toggle blockComment command in vscode.

Did you get intellisense for `comments.lineComment` after typing `liquid.` ?  You shouldn't unless you have a liquid extension that supports lineComments.  [Liquid](https://marketplace.visualstudio.com/items?itemName=sissel.shopify-liquid) does not support line comments.

**Comment by ianwieds** [comment]
I think that worked. The issue was that I had both `"liquid.comments.lineComment": ["<!--", "-->"],` and `"liquid.comments.blockComment": ["<!--", "-->"],`but after removing the `lineComment` it now works.

Thanks and great extension!
