### ISSUE TITLE
Comment character for 'batch' not working

### ISSUE THREAD

**Issue by agoragor** [ArturoDent/custom-comments#7]
Installed the extension and added this to settings.json:

"custom-language-properties": {
        "batch.comments.lineComment": ":: "
      }

But vscode still adds the comment prefix  

@REM

Any help would be appreciated.

**Comment by ArturoDent** [comment]
`bat` is the language ID for `batch` files.  Intellisense gives you a `bat` option (and no `batch` option).

When I use 

```
"bat.comments.lineComment": "::"
```

it works as expected.  You must use the language ID, I'll make that more clear in the README.

**Comment by agoragor** [comment]
Super!  Thank you very much!

I used the designation 'batch' that appears in the lower right corner of
the window.
As a new user of vscode, this is an important learning experience for me,
e.g., in the use of intellisense.

Thanks again!

**Comment by agoragor** [comment]
Awesome, thanks for the update!
