### ISSUE TITLE
Cannot activate extension because it depends on the 'Git' extension

### ISSUE THREAD

**Issue by jolsen-mitsu** [ArturoDent/custom-comments#8]
I installed this extension and I'm getting this error message:

`Cannot activate the 'Custom Language Properties' extension because it depends on the 'Git' extension, which is not loaded. Would you like to reload the window to load the extension?`

If I click `yes` the window reloads, but I get the same error message again.

I'm not sure why this extension would be dependent on a git extension, seems unrelated.

Is there something I can do to work around this problem?

**Comment by ArturoDent** [comment]
I have no idea how that dependency got there?  I have removed it and just published the updated version v0.6.6.

Let me know if it removes that error situation.  Thanks.

**Comment by jolsen-mitsu** [comment]
Looks like it's resolved. Thanks!
